### ISSUE TITLE
SSR issue with the ChartPie

### ISSUE THREAD

**Issue by amjadkhan896** [d2bjs/vue-d2b#6]
Hi, 
I am using vue-d2b for my project to show the PieChart. I my plugin folder i am loading the code is 
```
import Vue from 'vue'

//import { ChartPie } from 'vue-d2b'

  var Vued2b = require('vue-d2b');

 Vue.use(Vued2b);
```
I already registered my plugin also in nuxt.config.js like 
```
  {src:'~/plugins/vue-d2b', ssr: false },
```

But i am still facing the issue of " Unknown custom element: <chart-pie> - did you register the component correctly" in the console.
Any suggestion for this.
Thanks

**Comment by kevinwarne** [comment]
Hey,

There is no need to do `Vue.use(Vued2b)`. Vue d2b is not strictly a vue plugin it is a collection of vue components. 

So you can import the components like: 
```javascript 
  import { ChartPie } from 'vue-d2b'
```

And then register them in the vue instance like:
```javascript
  export default {
    components: {
      ChartAxis
    }
  }
```

You can refer here for more specifics on rendering the vue d2b pie chart: http://docs.d2bjs.org/vue-d2b/#/pie

**Comment by kevinwarne** [comment]
One more not on this you can also register the component globally by doing:

```javascript
  import { ChartPie } from 'vue-d2b'
  Vue.component('chart-axis', ChartAxis)
```

**Comment by amjadkhan896** [comment]
Thanks @kevinwarne,
The first solution you provide failed. The second solution worked for me, But in the production environment. 

In the dev environment, I am facing the below error as I attached. 
Is there a way to resolve the below error. Thanks once again for your response
<img width="1313" alt="screen shot 2019-01-24 at 10 06 58 am" src="https://user-images.githubusercontent.com/11747524/51657953-d4263880-1fbf-11e9-8850-c29bcc34e4ec.png">

**Comment by kevinwarne** [comment]
Hmm, I haven't used vue-d2b with a SSR implementation yet. But I think I'm beginning to see the problem. 

With [nuxt](https://nuxtjs.org/api/components-no-ssr/) you can escape from ssr rendering with the `no-ssr` tag:

```html
<no-ssr>
  <chart-pie></chart-pie>
</no-ssr>
```

One more post related to your specific error is here [https://github.com/vuejs-templates/webpack/issues/215](https://github.com/vuejs-templates/webpack/issues/215). Since vue-d2b does have some javascript included templates I've gone ahead moved it all to `.vue` files which should remove that error you were receiving. Update to the latest vue-d2b version `1.0.15`.

Cheers

**Comment by kevinwarne** [comment]
Good to hear! I'll close this now.

**Comment by ikluhsman** [comment]
I know this is closed and not related to vue-d2b, but to make it easy for future viewers as this was a Nuxt issue, if you're using nuxt >v2.9.0 use client-only instead of no-ssr. https://nuxtjs.org/api/components-client-only/
